# Generated by Django 3.2.9 on 2021-12-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_remove_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
